In [1]:
from fbprophet.diagnostics import cross_validation, performance_metrics
import itertools

road = '10'

new_df = pd.DataFrame({
    'ds':new_train['날짜'],
    'y':new_train[road]
})

In [2]:
import os
import warnings

import pandas as pd
from datetime import datetime

from fbprophet import Prophet
from fbprophet.plot import plot_plotly

import numpy as np
import matplotlib.pyplot as plt

pd.set_option('display.max_row', 100)
pd.set_option('display.max_column', 37)
warnings.filterwarnings(action='ignore')

In [3]:
DATA_DIR = os.path.abspath(os.path.dirname('EDA.ipynb') + 'data' + '/EDA')

In [4]:
train_df = pd.read_csv(os.path.join(DATA_DIR, 'train', 'train.csv'))
valid_df = pd.read_csv(os.path.join(DATA_DIR, 'train', 'validate.csv'))

In [5]:
test_df = pd.read_csv(os.path.join(DATA_DIR, 'test', 'test.csv'))
submission = pd.read_csv(os.path.join(DATA_DIR, 'sample_submission.csv'))

In [6]:
def convert(date):
    return date[:4] + '-' + date[4:6] + '-' + date[6:]

def date_to_timestamp(df):
    new_df = df.copy()
    
    date_series = new_df['날짜'].astype(str).map(convert)
    time_series = new_df['시간'].astype(str).map(lambda x: ' ' + x.zfill(2) + ':00:00')
    
    new_df['날짜'] = date_series + time_series
    
    new_df['날짜'] = pd.to_datetime(new_df['날짜'])
    new_df.drop(['시간'], axis=1, inplace=True)
    
    return new_df

In [7]:
train = date_to_timestamp(train_df)
train

                      날짜        10       100      101      120      121  \
0    2020-01-01 00:00:00   83247.0   19128.0   2611.0   5161.0   1588.0
1    2020-01-01 01:00:00   89309.0   19027.0   3337.0   5502.0   1650.0
2    2020-01-01 02:00:00   66611.0   14710.0   2970.0   4631.0   1044.0
3    2020-01-01 03:00:00   53290.0   13753.0   2270.0   4242.0   1021.0
4    2020-01-01 04:00:00   52095.0   17615.0   2406.0   3689.0   1840.0
...                  ...       ...       ...      ...      ...      ...
3307 2020-05-17 19:00:00  311727.0  101285.0  10085.0  30637.0  10060.0
3308 2020-05-17 20:00:00  305354.0   91426.0   8607.0  26021.0   8095.0
3309 2020-05-17 21:00:00  306008.0   75113.0   6325.0  19933.0   5711.0
3310 2020-05-17 22:00:00  237447.0   49498.0   4209.0  12145.0   3891.0
3311 2020-05-17 23:00:00  150312.0   27410.0   2350.0   6406.0   1803.0

         140       150     160      200     201      251      270      300  \
0      892.0   32263.0  1636.0   7938.0  1894.0  14957.0   3527.0  11174.0
1     1043.0   35609.0  1644.0   9896.0  1967.0  14682.0   3420.0  13884.0
2      921.0   26821.0  1104.0   9343.0  1838.0  11120.0   3587.0  17141.0
3      790.0   21322.0   909.0  10009.0  1630.0   9836.0   3842.0  20715.0
4      922.0   22711.0  1354.0  15497.0  1264.0  10668.0   4559.0  28308.0
...      ...       ...     ...      ...     ...      ...      ...      ...
3307  8749.0  148935.0  6801.0  26101.0  9370.0  74169.0  17764.0  34715.0
3308  7198.0  136503.0  6147.0  20759.0  8432.0  68923.0  14593.0  30279.0
3309  4494.0  129412.0  5134.0  14496.0  6739.0  54455.0  11997.0  27047.0
3310  2718.0   96698.0  3526.0   9363.0  4543.0  35618.0   7996.0  19478.0
3311  1614.0   55788.0  1849.0   5722.0  2611.0  21993.0   4567.0  12547.0

          301      351      352      370      400      450      500      550  \
0      2930.0   8640.0  14175.0   2035.0   5231.0  18492.0  48520.0  15393.0
1      3062.0   8349.0  15654.0   2417.0   5483.0  15283.0  57904.0  15834.0
2      3255.0   7025.0  12520.0   1859.0   5058.0  14327.0  53876.0  13866.0
3      2661.0   7226.0   9821.0   1724.0   4863.0  12787.0  51615.0  13528.0
4      2894.0   8201.0   9038.0    960.0   5166.0  11479.0  47424.0  18156.0
...       ...      ...      ...      ...      ...      ...      ...      ...
3307  19806.0  42734.0  63382.0  14130.0  34866.0  71475.0  96849.0  79150.0
3308  17634.0  37661.0  57815.0  13055.0  31943.0  65378.0  92116.0  72379.0
3309  15943.0  29029.0  54627.0  12292.0  27424.0  60696.0  83628.0  57866.0
3310  10010.0  18663.0  39694.0   8818.0  17770.0  45983.0  57321.0  35250.0
3311   5756.0  10595.0  21670.0   5379.0  10185.0  31934.0  33200.0  19428.0

          600      650      652      1000    1020     1040     1100     1200  \
0     16628.0   8804.0   2790.0   38657.0  1311.0   3482.0  11299.0   7072.0
1     19785.0   8483.0   3381.0   45759.0  1162.0   3849.0  13180.0   8771.0
2     24501.0   8167.0   2670.0   27425.0   768.0   2299.0   7986.0   5426.0
3     28695.0   9459.0   2325.0   18893.0   632.0   1716.0   5703.0   3156.0
4     26977.0  10944.0   3583.0   18135.0   875.0   2421.0   5816.0   2933.0
...       ...      ...      ...       ...     ...      ...      ...      ...
3307  25109.0  14680.0  10465.0  128344.0  6726.0  15431.0  25597.0  14292.0
3308  23165.0  11879.0   9135.0  131682.0  5501.0  15378.0  24661.0  14747.0
3309  16629.0   8573.0   6488.0  127826.0  4216.0  12558.0  22781.0  14081.0
3310  10761.0   5331.0   4109.0   94288.0  2578.0   8870.0  16640.0  11066.0
3311   5395.0   3256.0   2499.0   52917.0  1377.0   5021.0  10058.0   7139.0

        1510     2510    3000     4510     5510     6000
0     1176.0   3810.0   748.0   3920.0   2133.0   3799.0
1     1283.0   3763.0   782.0   3483.0   2057.0   4010.0
2     1536.0   3229.0   491.0   2634.0   1526.0   3388.0
3     1104.0   2882.0   431.0   2488.0   1268.0   3686.0
4     1206.0   2433.0   499.0   2952.0   1927.0   5608.0
...      ...      ...     ...      ...      ...      ...
3307  9300.0  22238.0  3786.0  16936.0  10729.0  20194.0
3308  8239.0  20604.0  3203.0  15018.0   9767.0  17962.0
3309  6392.0  17937.0  2447.0  12403.0   7825.0  14031.0
3310  4427.0  11955.0  1495.0   7507.0   5387.0   8889.0
3311  2250.0   6844.0   735.0   4116.0   3046.0   4606.0

[3312 rows x 36 columns]

In [8]:
valid = date_to_timestamp(valid_df)
valid[168:]

                     날짜      10      100      101      120     121     140  \
168 2020-05-18 00:00:00   82065  15172.0   1500.0   3294.0  1086.0   962.0
169 2020-05-18 01:00:00   51248   9840.0    813.0   2356.0   696.0   546.0
170 2020-05-18 02:00:00   39026   7894.0    760.0   2413.0   408.0   549.0
171 2020-05-18 03:00:00   40993  10137.0    780.0   2701.0   420.0   741.0
172 2020-05-18 04:00:00   77863  19603.0   1276.0   5019.0   968.0  1160.0
..                  ...     ...      ...      ...      ...     ...     ...
331 2020-05-24 19:00:00  314226  98345.0  10625.0  28618.0  8316.0  6684.0
332 2020-05-24 20:00:00  300001  87871.0   8226.0  22706.0  6981.0  5743.0
333 2020-05-24 21:00:00  304150  71126.0   6002.0  18317.0  4939.0  3779.0
334 2020-05-24 22:00:00  236751  44947.0   3575.0  11455.0  3135.0  2536.0
335 2020-05-24 23:00:00  143609  26137.0   2242.0   6166.0  1609.0  1391.0

        150     160    200     201      251      270      300      301  \
168   28931  1103.0   3014  1619.0  12596.0   3060.0   7383.0   2958.0
169   17888   720.0   1839  1502.0   7741.0   2132.0   4790.0   1743.0
170   13357   498.0   1360  1233.0   6475.0   2098.0   3965.0   1345.0
171   15544   532.0   1671  1800.0   7720.0   2133.0   4083.0   1501.0
172   32101   968.0   2574  2384.0  12018.0   3502.0   6430.0   2882.0
..      ...     ...    ...     ...      ...      ...      ...      ...
331  141675  6619.0  23535  8572.0  67748.0  16791.0  33325.0  19124.0
332  142933  6295.0  20953  7851.0  61609.0  14119.0  30216.0  18610.0
333  133110  4781.0  15242  6101.0  48336.0  11534.0  25710.0  15651.0
334   98582  3267.0   8849  4553.0  33607.0   8069.0  18293.0   9723.0
335   54633  1899.0   5182  2422.0  20343.0   5104.0  11331.0   5413.0

         351      352      370    400      450     500      550    600  \
168   5829.0  11297.0   2890.0   5694  19553.0   18919   9907.0   2912
169   4296.0   6781.0   1752.0   3651  12454.0   11849   6292.0   1750
170   3957.0   4762.0   1250.0   3199   9640.0    9392   4961.0   1104
171   3992.0   6202.0   1505.0   4459  10802.0   11664   6015.0   1132
172   5957.0  11987.0   3176.0   9054  16490.0   23479  10676.0   1945
..       ...      ...      ...    ...      ...     ...      ...    ...
331  42183.0  63229.0  13163.0  35383  73188.0  100849  84286.0  26458
332  35556.0  59070.0  12788.0  30675  68255.0   95107  76441.0  24140
333  27467.0  53787.0  12019.0  26317  61169.0   86434  61136.0  21076
334  16602.0  38615.0   8703.0  17694  47609.0   58492  37501.0  12090
335   9455.0  22150.0   5370.0  10032  31124.0   34013  20205.0   6104

         650    652      1000    1020     1040     1100   1200    1510   2510  \
168   1884.0   1112   28189.0   618.0   2790.0   5147.0   4331  1329.0   3665
169   1118.0    703   16683.0   430.0   1864.0   3269.0   2561   921.0   2081
170   1004.0    485   11934.0   322.0   1313.0   2765.0   1931   920.0   1764
171   1061.0    851   13458.0   326.0   1766.0   3320.0   2060   892.0   2447
172   1520.0   1420   31698.0   669.0   2914.0   6986.0   3911  1368.0   4380
..       ...    ...       ...     ...      ...      ...    ...     ...    ...
331  15572.0  10341  139827.0  8254.0  16118.0  23304.0  14082  8447.0  21694
332  13340.0   8872  142469.0  5225.0  15297.0  21919.0  14526  7332.0  19732
333   9317.0   6392  138816.0  4072.0  12685.0  21135.0  14403  5443.0  16967
334   5901.0   3938  100767.0  2489.0   8093.0  14427.0  10914  3861.0  11397
335   3782.0   2272   55574.0  1343.0   4686.0   8732.0   6986  2161.0   6487

       3000     4510     5510   6000
168   404.0   2242.0   1619.0   2314
169   272.0   1390.0   1003.0   1766
170   228.0   1136.0    922.0   1309
171   337.0   1495.0    975.0   1912
172   513.0   2940.0   1758.0   3629
..      ...      ...      ...    ...
331  2180.0  15746.0  10903.0  21014
332  1990.0  14096.0  10028.0  17787
333  1359.0  11670.0   7963.0  14041
334   859.0   7270.0   5194.0   8230
335   410.0   3963.0   2686.0   4690

[168 rows x 36 columns]

In [9]:
test = date_to_timestamp(test_df)
test.head()

                   날짜     10    100     101   120     121     140    150  \
0 2020-05-18 00:00:00  82065  15172  1500.0  3294  1086.0   962.0  28931
1 2020-05-18 01:00:00  51248   9840   813.0  2356   696.0   546.0  17888
2 2020-05-18 02:00:00  39026   7894   760.0  2413   408.0   549.0  13357
3 2020-05-18 03:00:00  40993  10137   780.0  2701   420.0   741.0  15544
4 2020-05-18 04:00:00  77863  19603  1276.0  5019   968.0  1160.0  32101

    160   200   201    251   270   300   301   351    352   370   400    450  \
0  1103  3014  1619  12596  3060  7383  2958  5829  11297  2890  5694  19553
1   720  1839  1502   7741  2132  4790  1743  4296   6781  1752  3651  12454
2   498  1360  1233   6475  2098  3965  1345  3957   4762  1250  3199   9640
3   532  1671  1800   7720  2133  4083  1501  3992   6202  1505  4459  10802
4   968  2574  2384  12018  3502  6430  2882  5957  11987  3176  9054  16490

     500    550   600   650   652   1000  1020  1040  1100  1200  1510  2510  \
0  18919   9907  2912  1884  1112  28189   618  2790  5147  4331  1329  3665
1  11849   6292  1750  1118   703  16683   430  1864  3269  2561   921  2081
2   9392   4961  1104  1004   485  11934   322  1313  2765  1931   920  1764
3  11664   6015  1132  1061   851  13458   326  1766  3320  2060   892  2447
4  23479  10676  1945  1520  1420  31698   669  2914  6986  3911  1368  4380

   3000  4510  5510  6000
0   404  2242  1619  2314
1   272  1390  1003  1766
2   228  1136   922  1309
3   337  1495   975  1912
4   513  2940  1758  3629

In [10]:
submission

       timestamp   10  100  101  120  121  140  150  160  200  201  251  270  \
0     20200525_0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1     20200525_1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2     20200525_2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3     20200525_3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4     20200525_4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
..           ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
163  20200531_19  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
164  20200531_20  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
165  20200531_21  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
166  20200531_22  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
167  20200531_23  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

     300  301  351  352  370  400  450  500  550  600  650  652  1000  1020  \
0    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
1    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
2    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
3    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
4    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   ...   ...
163  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
164  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
165  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
166  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0
167  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0   0.0

     1040  1100  1200  1510  2510  3000  4510  5510  6000
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
..    ...   ...   ...   ...   ...   ...   ...   ...   ...
163   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
164   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
165   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
166   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
167   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0

[168 rows x 36 columns]

In [11]:
# train + valid
new_train = pd.concat([train, valid[168:]])
new_train

                     날짜        10      100      101      120     121     140  \
0   2020-01-01 00:00:00   83247.0  19128.0   2611.0   5161.0  1588.0   892.0
1   2020-01-01 01:00:00   89309.0  19027.0   3337.0   5502.0  1650.0  1043.0
2   2020-01-01 02:00:00   66611.0  14710.0   2970.0   4631.0  1044.0   921.0
3   2020-01-01 03:00:00   53290.0  13753.0   2270.0   4242.0  1021.0   790.0
4   2020-01-01 04:00:00   52095.0  17615.0   2406.0   3689.0  1840.0   922.0
..                  ...       ...      ...      ...      ...     ...     ...
331 2020-05-24 19:00:00  314226.0  98345.0  10625.0  28618.0  8316.0  6684.0
332 2020-05-24 20:00:00  300001.0  87871.0   8226.0  22706.0  6981.0  5743.0
333 2020-05-24 21:00:00  304150.0  71126.0   6002.0  18317.0  4939.0  3779.0
334 2020-05-24 22:00:00  236751.0  44947.0   3575.0  11455.0  3135.0  2536.0
335 2020-05-24 23:00:00  143609.0  26137.0   2242.0   6166.0  1609.0  1391.0

          150     160      200     201      251      270      300      301  \
0     32263.0  1636.0   7938.0  1894.0  14957.0   3527.0  11174.0   2930.0
1     35609.0  1644.0   9896.0  1967.0  14682.0   3420.0  13884.0   3062.0
2     26821.0  1104.0   9343.0  1838.0  11120.0   3587.0  17141.0   3255.0
3     21322.0   909.0  10009.0  1630.0   9836.0   3842.0  20715.0   2661.0
4     22711.0  1354.0  15497.0  1264.0  10668.0   4559.0  28308.0   2894.0
..        ...     ...      ...     ...      ...      ...      ...      ...
331  141675.0  6619.0  23535.0  8572.0  67748.0  16791.0  33325.0  19124.0
332  142933.0  6295.0  20953.0  7851.0  61609.0  14119.0  30216.0  18610.0
333  133110.0  4781.0  15242.0  6101.0  48336.0  11534.0  25710.0  15651.0
334   98582.0  3267.0   8849.0  4553.0  33607.0   8069.0  18293.0   9723.0
335   54633.0  1899.0   5182.0  2422.0  20343.0   5104.0  11331.0   5413.0

         351      352      370      400      450       500      550      600  \
0     8640.0  14175.0   2035.0   5231.0  18492.0   48520.0  15393.0  16628.0
1     8349.0  15654.0   2417.0   5483.0  15283.0   57904.0  15834.0  19785.0
2     7025.0  12520.0   1859.0   5058.0  14327.0   53876.0  13866.0  24501.0
3     7226.0   9821.0   1724.0   4863.0  12787.0   51615.0  13528.0  28695.0
4     8201.0   9038.0    960.0   5166.0  11479.0   47424.0  18156.0  26977.0
..       ...      ...      ...      ...      ...       ...      ...      ...
331  42183.0  63229.0  13163.0  35383.0  73188.0  100849.0  84286.0  26458.0
332  35556.0  59070.0  12788.0  30675.0  68255.0   95107.0  76441.0  24140.0
333  27467.0  53787.0  12019.0  26317.0  61169.0   86434.0  61136.0  21076.0
334  16602.0  38615.0   8703.0  17694.0  47609.0   58492.0  37501.0  12090.0
335   9455.0  22150.0   5370.0  10032.0  31124.0   34013.0  20205.0   6104.0

         650      652      1000    1020     1040     1100     1200    1510  \
0     8804.0   2790.0   38657.0  1311.0   3482.0  11299.0   7072.0  1176.0
1     8483.0   3381.0   45759.0  1162.0   3849.0  13180.0   8771.0  1283.0
2     8167.0   2670.0   27425.0   768.0   2299.0   7986.0   5426.0  1536.0
3     9459.0   2325.0   18893.0   632.0   1716.0   5703.0   3156.0  1104.0
4    10944.0   3583.0   18135.0   875.0   2421.0   5816.0   2933.0  1206.0
..       ...      ...       ...     ...      ...      ...      ...     ...
331  15572.0  10341.0  139827.0  8254.0  16118.0  23304.0  14082.0  8447.0
332  13340.0   8872.0  142469.0  5225.0  15297.0  21919.0  14526.0  7332.0
333   9317.0   6392.0  138816.0  4072.0  12685.0  21135.0  14403.0  5443.0
334   5901.0   3938.0  100767.0  2489.0   8093.0  14427.0  10914.0  3861.0
335   3782.0   2272.0   55574.0  1343.0   4686.0   8732.0   6986.0  2161.0

        2510    3000     4510     5510     6000
0     3810.0   748.0   3920.0   2133.0   3799.0
1     3763.0   782.0   3483.0   2057.0   4010.0
2     3229.0   491.0   2634.0   1526.0   3388.0
3     2882.0   431.0   2488.0   1268.0   3686.0
4     2433.0   499.0   2952.0   1927.0   5608.0
..       ...     ...      ...      ...      ...
331  21694.0  2180.0  15746.0  10903.0  21014.0
332  19732.0  1990.0  14096.0  10028.0  17787.0
333  16967.0  1359.0  11670.0   7963.0  14041.0
334  11397.0   859.0   7270.0   5194.0   8230.0
335   6487.0   410.0   3963.0   2686.0   4690.0

[3480 rows x 36 columns]

In [12]:
new_train = pd.concat([train, valid[168:]])
new_train

                     날짜        10      100      101      120     121     140  \
0   2020-01-01 00:00:00   83247.0  19128.0   2611.0   5161.0  1588.0   892.0
1   2020-01-01 01:00:00   89309.0  19027.0   3337.0   5502.0  1650.0  1043.0
2   2020-01-01 02:00:00   66611.0  14710.0   2970.0   4631.0  1044.0   921.0
3   2020-01-01 03:00:00   53290.0  13753.0   2270.0   4242.0  1021.0   790.0
4   2020-01-01 04:00:00   52095.0  17615.0   2406.0   3689.0  1840.0   922.0
..                  ...       ...      ...      ...      ...     ...     ...
331 2020-05-24 19:00:00  314226.0  98345.0  10625.0  28618.0  8316.0  6684.0
332 2020-05-24 20:00:00  300001.0  87871.0   8226.0  22706.0  6981.0  5743.0
333 2020-05-24 21:00:00  304150.0  71126.0   6002.0  18317.0  4939.0  3779.0
334 2020-05-24 22:00:00  236751.0  44947.0   3575.0  11455.0  3135.0  2536.0
335 2020-05-24 23:00:00  143609.0  26137.0   2242.0   6166.0  1609.0  1391.0

          150     160      200     201      251      270      300      301  \
0     32263.0  1636.0   7938.0  1894.0  14957.0   3527.0  11174.0   2930.0
1     35609.0  1644.0   9896.0  1967.0  14682.0   3420.0  13884.0   3062.0
2     26821.0  1104.0   9343.0  1838.0  11120.0   3587.0  17141.0   3255.0
3     21322.0   909.0  10009.0  1630.0   9836.0   3842.0  20715.0   2661.0
4     22711.0  1354.0  15497.0  1264.0  10668.0   4559.0  28308.0   2894.0
..        ...     ...      ...     ...      ...      ...      ...      ...
331  141675.0  6619.0  23535.0  8572.0  67748.0  16791.0  33325.0  19124.0
332  142933.0  6295.0  20953.0  7851.0  61609.0  14119.0  30216.0  18610.0
333  133110.0  4781.0  15242.0  6101.0  48336.0  11534.0  25710.0  15651.0
334   98582.0  3267.0   8849.0  4553.0  33607.0   8069.0  18293.0   9723.0
335   54633.0  1899.0   5182.0  2422.0  20343.0   5104.0  11331.0   5413.0

         351      352      370      400      450       500      550      600  \
0     8640.0  14175.0   2035.0   5231.0  18492.0   48520.0  15393.0  16628.0
1     8349.0  15654.0   2417.0   5483.0  15283.0   57904.0  15834.0  19785.0
2     7025.0  12520.0   1859.0   5058.0  14327.0   53876.0  13866.0  24501.0
3     7226.0   9821.0   1724.0   4863.0  12787.0   51615.0  13528.0  28695.0
4     8201.0   9038.0    960.0   5166.0  11479.0   47424.0  18156.0  26977.0
..       ...      ...      ...      ...      ...       ...      ...      ...
331  42183.0  63229.0  13163.0  35383.0  73188.0  100849.0  84286.0  26458.0
332  35556.0  59070.0  12788.0  30675.0  68255.0   95107.0  76441.0  24140.0
333  27467.0  53787.0  12019.0  26317.0  61169.0   86434.0  61136.0  21076.0
334  16602.0  38615.0   8703.0  17694.0  47609.0   58492.0  37501.0  12090.0
335   9455.0  22150.0   5370.0  10032.0  31124.0   34013.0  20205.0   6104.0

         650      652      1000    1020     1040     1100     1200    1510  \
0     8804.0   2790.0   38657.0  1311.0   3482.0  11299.0   7072.0  1176.0
1     8483.0   3381.0   45759.0  1162.0   3849.0  13180.0   8771.0  1283.0
2     8167.0   2670.0   27425.0   768.0   2299.0   7986.0   5426.0  1536.0
3     9459.0   2325.0   18893.0   632.0   1716.0   5703.0   3156.0  1104.0
4    10944.0   3583.0   18135.0   875.0   2421.0   5816.0   2933.0  1206.0
..       ...      ...       ...     ...      ...      ...      ...     ...
331  15572.0  10341.0  139827.0  8254.0  16118.0  23304.0  14082.0  8447.0
332  13340.0   8872.0  142469.0  5225.0  15297.0  21919.0  14526.0  7332.0
333   9317.0   6392.0  138816.0  4072.0  12685.0  21135.0  14403.0  5443.0
334   5901.0   3938.0  100767.0  2489.0   8093.0  14427.0  10914.0  3861.0
335   3782.0   2272.0   55574.0  1343.0   4686.0   8732.0   6986.0  2161.0

        2510    3000     4510     5510     6000
0     3810.0   748.0   3920.0   2133.0   3799.0
1     3763.0   782.0   3483.0   2057.0   4010.0
2     3229.0   491.0   2634.0   1526.0   3388.0
3     2882.0   431.0   2488.0   1268.0   3686.0
4     2433.0   499.0   2952.0   1927.0   5608.0
..       ...     ...      ...      ...      ...
331  21694.0  2180.0  15746.0  10903.0  21014.0
332  19732.0  1990.0  14096.0  10028.0  17787.0
333  16967.0  1359.0  11670.0   7963.0  14041.0
334  11397.0   859.0   7270.0   5194.0   8230.0
335   6487.0   410.0   3963.0   2686.0   4690.0

[3480 rows x 36 columns]

In [13]:
new_train = pd.concat([train, valid[168:]])
new_train.head()

                   날짜       10      100     101     120     121     140  \
0 2020-01-01 00:00:00  83247.0  19128.0  2611.0  5161.0  1588.0   892.0
1 2020-01-01 01:00:00  89309.0  19027.0  3337.0  5502.0  1650.0  1043.0
2 2020-01-01 02:00:00  66611.0  14710.0  2970.0  4631.0  1044.0   921.0
3 2020-01-01 03:00:00  53290.0  13753.0  2270.0  4242.0  1021.0   790.0
4 2020-01-01 04:00:00  52095.0  17615.0  2406.0  3689.0  1840.0   922.0

       150     160      200     201      251     270      300     301     351  \
0  32263.0  1636.0   7938.0  1894.0  14957.0  3527.0  11174.0  2930.0  8640.0
1  35609.0  1644.0   9896.0  1967.0  14682.0  3420.0  13884.0  3062.0  8349.0
2  26821.0  1104.0   9343.0  1838.0  11120.0  3587.0  17141.0  3255.0  7025.0
3  21322.0   909.0  10009.0  1630.0   9836.0  3842.0  20715.0  2661.0  7226.0
4  22711.0  1354.0  15497.0  1264.0  10668.0  4559.0  28308.0  2894.0  8201.0

       352     370     400      450      500      550      600      650  \
0  14175.0  2035.0  5231.0  18492.0  48520.0  15393.0  16628.0   8804.0
1  15654.0  2417.0  5483.0  15283.0  57904.0  15834.0  19785.0   8483.0
2  12520.0  1859.0  5058.0  14327.0  53876.0  13866.0  24501.0   8167.0
3   9821.0  1724.0  4863.0  12787.0  51615.0  13528.0  28695.0   9459.0
4   9038.0   960.0  5166.0  11479.0  47424.0  18156.0  26977.0  10944.0

      652     1000    1020    1040     1100    1200    1510    2510   3000  \
0  2790.0  38657.0  1311.0  3482.0  11299.0  7072.0  1176.0  3810.0  748.0
1  3381.0  45759.0  1162.0  3849.0  13180.0  8771.0  1283.0  3763.0  782.0
2  2670.0  27425.0   768.0  2299.0   7986.0  5426.0  1536.0  3229.0  491.0
3  2325.0  18893.0   632.0  1716.0   5703.0  3156.0  1104.0  2882.0  431.0
4  3583.0  18135.0   875.0  2421.0   5816.0  2933.0  1206.0  2433.0  499.0

     4510    5510    6000
0  3920.0  2133.0  3799.0
1  3483.0  2057.0  4010.0
2  2634.0  1526.0  3388.0
3  2488.0  1268.0  3686.0
4  2952.0  1927.0  5608.0

In [14]:
new_train = pd.concat([train, valid[168:]])
new_train.tail()

                     날짜        10      100      101      120     121     140  \
331 2020-05-24 19:00:00  314226.0  98345.0  10625.0  28618.0  8316.0  6684.0
332 2020-05-24 20:00:00  300001.0  87871.0   8226.0  22706.0  6981.0  5743.0
333 2020-05-24 21:00:00  304150.0  71126.0   6002.0  18317.0  4939.0  3779.0
334 2020-05-24 22:00:00  236751.0  44947.0   3575.0  11455.0  3135.0  2536.0
335 2020-05-24 23:00:00  143609.0  26137.0   2242.0   6166.0  1609.0  1391.0

          150     160      200     201      251      270      300      301  \
331  141675.0  6619.0  23535.0  8572.0  67748.0  16791.0  33325.0  19124.0
332  142933.0  6295.0  20953.0  7851.0  61609.0  14119.0  30216.0  18610.0
333  133110.0  4781.0  15242.0  6101.0  48336.0  11534.0  25710.0  15651.0
334   98582.0  3267.0   8849.0  4553.0  33607.0   8069.0  18293.0   9723.0
335   54633.0  1899.0   5182.0  2422.0  20343.0   5104.0  11331.0   5413.0

         351      352      370      400      450       500      550      600  \
331  42183.0  63229.0  13163.0  35383.0  73188.0  100849.0  84286.0  26458.0
332  35556.0  59070.0  12788.0  30675.0  68255.0   95107.0  76441.0  24140.0
333  27467.0  53787.0  12019.0  26317.0  61169.0   86434.0  61136.0  21076.0
334  16602.0  38615.0   8703.0  17694.0  47609.0   58492.0  37501.0  12090.0
335   9455.0  22150.0   5370.0  10032.0  31124.0   34013.0  20205.0   6104.0

         650      652      1000    1020     1040     1100     1200    1510  \
331  15572.0  10341.0  139827.0  8254.0  16118.0  23304.0  14082.0  8447.0
332  13340.0   8872.0  142469.0  5225.0  15297.0  21919.0  14526.0  7332.0
333   9317.0   6392.0  138816.0  4072.0  12685.0  21135.0  14403.0  5443.0
334   5901.0   3938.0  100767.0  2489.0   8093.0  14427.0  10914.0  3861.0
335   3782.0   2272.0   55574.0  1343.0   4686.0   8732.0   6986.0  2161.0

        2510    3000     4510     5510     6000
331  21694.0  2180.0  15746.0  10903.0  21014.0
332  19732.0  1990.0  14096.0  10028.0  17787.0
333  16967.0  1359.0  11670.0   7963.0  14041.0
334  11397.0   859.0   7270.0   5194.0   8230.0
335   6487.0   410.0   3963.0   2686.0   4690.0

In [15]:
new_train

                     날짜        10      100      101      120     121     140  \
0   2020-01-01 00:00:00   83247.0  19128.0   2611.0   5161.0  1588.0   892.0
1   2020-01-01 01:00:00   89309.0  19027.0   3337.0   5502.0  1650.0  1043.0
2   2020-01-01 02:00:00   66611.0  14710.0   2970.0   4631.0  1044.0   921.0
3   2020-01-01 03:00:00   53290.0  13753.0   2270.0   4242.0  1021.0   790.0
4   2020-01-01 04:00:00   52095.0  17615.0   2406.0   3689.0  1840.0   922.0
..                  ...       ...      ...      ...      ...     ...     ...
331 2020-05-24 19:00:00  314226.0  98345.0  10625.0  28618.0  8316.0  6684.0
332 2020-05-24 20:00:00  300001.0  87871.0   8226.0  22706.0  6981.0  5743.0
333 2020-05-24 21:00:00  304150.0  71126.0   6002.0  18317.0  4939.0  3779.0
334 2020-05-24 22:00:00  236751.0  44947.0   3575.0  11455.0  3135.0  2536.0
335 2020-05-24 23:00:00  143609.0  26137.0   2242.0   6166.0  1609.0  1391.0

          150     160      200     201      251      270      300      301  \
0     32263.0  1636.0   7938.0  1894.0  14957.0   3527.0  11174.0   2930.0
1     35609.0  1644.0   9896.0  1967.0  14682.0   3420.0  13884.0   3062.0
2     26821.0  1104.0   9343.0  1838.0  11120.0   3587.0  17141.0   3255.0
3     21322.0   909.0  10009.0  1630.0   9836.0   3842.0  20715.0   2661.0
4     22711.0  1354.0  15497.0  1264.0  10668.0   4559.0  28308.0   2894.0
..        ...     ...      ...     ...      ...      ...      ...      ...
331  141675.0  6619.0  23535.0  8572.0  67748.0  16791.0  33325.0  19124.0
332  142933.0  6295.0  20953.0  7851.0  61609.0  14119.0  30216.0  18610.0
333  133110.0  4781.0  15242.0  6101.0  48336.0  11534.0  25710.0  15651.0
334   98582.0  3267.0   8849.0  4553.0  33607.0   8069.0  18293.0   9723.0
335   54633.0  1899.0   5182.0  2422.0  20343.0   5104.0  11331.0   5413.0

         351      352      370      400      450       500      550      600  \
0     8640.0  14175.0   2035.0   5231.0  18492.0   48520.0  15393.0  16628.0
1     8349.0  15654.0   2417.0   5483.0  15283.0   57904.0  15834.0  19785.0
2     7025.0  12520.0   1859.0   5058.0  14327.0   53876.0  13866.0  24501.0
3     7226.0   9821.0   1724.0   4863.0  12787.0   51615.0  13528.0  28695.0
4     8201.0   9038.0    960.0   5166.0  11479.0   47424.0  18156.0  26977.0
..       ...      ...      ...      ...      ...       ...      ...      ...
331  42183.0  63229.0  13163.0  35383.0  73188.0  100849.0  84286.0  26458.0
332  35556.0  59070.0  12788.0  30675.0  68255.0   95107.0  76441.0  24140.0
333  27467.0  53787.0  12019.0  26317.0  61169.0   86434.0  61136.0  21076.0
334  16602.0  38615.0   8703.0  17694.0  47609.0   58492.0  37501.0  12090.0
335   9455.0  22150.0   5370.0  10032.0  31124.0   34013.0  20205.0   6104.0

         650      652      1000    1020     1040     1100     1200    1510  \
0     8804.0   2790.0   38657.0  1311.0   3482.0  11299.0   7072.0  1176.0
1     8483.0   3381.0   45759.0  1162.0   3849.0  13180.0   8771.0  1283.0
2     8167.0   2670.0   27425.0   768.0   2299.0   7986.0   5426.0  1536.0
3     9459.0   2325.0   18893.0   632.0   1716.0   5703.0   3156.0  1104.0
4    10944.0   3583.0   18135.0   875.0   2421.0   5816.0   2933.0  1206.0
..       ...      ...       ...     ...      ...      ...      ...     ...
331  15572.0  10341.0  139827.0  8254.0  16118.0  23304.0  14082.0  8447.0
332  13340.0   8872.0  142469.0  5225.0  15297.0  21919.0  14526.0  7332.0
333   9317.0   6392.0  138816.0  4072.0  12685.0  21135.0  14403.0  5443.0
334   5901.0   3938.0  100767.0  2489.0   8093.0  14427.0  10914.0  3861.0
335   3782.0   2272.0   55574.0  1343.0   4686.0   8732.0   6986.0  2161.0

        2510    3000     4510     5510     6000
0     3810.0   748.0   3920.0   2133.0   3799.0
1     3763.0   782.0   3483.0   2057.0   4010.0
2     3229.0   491.0   2634.0   1526.0   3388.0
3     2882.0   431.0   2488.0   1268.0   3686.0
4     2433.0   499.0   2952.0   1927.0   5608.0
..       ...     ...      ...      ...      ...
331  21694.0  2180.0  15746.0  10903.0  21014.0
332  19732.0  1990.0  14096.0  10028.0  17787.0
333  16967.0  1359.0  11670.0   7963.0  14041.0
334  11397.0   859.0   7270.0   5194.0   8230.0
335   6487.0   410.0   3963.0   2686.0   4690.0

[3480 rows x 36 columns]

In [16]:
new_train.sum()

10      8.084463e+08
100     2.334008e+08
101     2.498295e+07
120     6.072151e+07
121     2.320340e+07
140     1.638828e+07
150     3.468841e+08
160     1.534875e+07
200     3.991463e+07
201     2.184572e+07
251     1.658647e+08
270     4.335454e+07
300     6.918029e+07
301     4.287005e+07
351     9.078815e+07
352     1.512508e+08
370     2.829656e+07
400     7.915625e+07
450     1.673313e+08
500     2.663589e+08
550     1.728434e+08
600     4.888724e+07
650     3.871080e+07
652     2.273921e+07
1000    3.859388e+08
1020    1.800264e+07
1040    3.824057e+07
1100    9.432077e+07
1200    4.865134e+07
1510    1.704667e+07
2510    5.120751e+07
3000    8.521900e+06
4510    4.240068e+07
5510    2.790702e+07
6000    4.885059e+07
dtype: float64

In [17]:
cluster_0 = [('101', '남해선(영암-순천)'), ('120', '광주대구선'), ('121', '무안광주선'), ('140', '고창담양선'), ('160', '울산선'), ('201', '익산장수선'), ('251', '호남선'), ('270', '순천완주선'), ('301', '당진대전선'), ('550', '중앙선'), ('652', '동해선(부산-포항)'), ('1020', '남해1지선'), ('2510', '호남지선')]
cluster_1 = [('10', '경부선'), ('100', '남해선(순천-부산)'), ('150', '서해안선'), ('352', '중부선'), ('370', '제2 중부선'), ('400', '평택제천선'), ('450', '중부내륙선'), ('500', '영동선'), ('1000', '서울외곽순환선'), ('1040', '남해2지선'), ('1100', '제2경인선'), ('1200', '경인선'), ('3000', '대전남부선'), ('4510', '중부내륙지선'), ('5510', '중앙선지선'), ('6000', '부산외곽선')]
cluster_2 = [('200', '대구포항선'), ('300', '청주영덕선'), ('351', '통영대전선'), ('600', '서울양양선'), ('650', '동해선(삼척-속초)'), ('1510', '서천공주선')]

In [18]:
import os
import warnings

import pandas as pd
from datetime import datetime

from fbprophet import Prophet
from fbprophet.plot import plot_plotly

import numpy as np
import matplotlib.pyplot as plt

import wandb

pd.set_option('display.max_row', 100)
pd.set_option('display.max_column', 37)
warnings.filterwarnings(action='ignore')

In [19]:
def create_timestamp(date):
    result = []
    
    for i in range(0, 24):
        result.append(date + ' ' + str(i).zfill(2) + ':00:00')
    
    return result

newyear = pd.DataFrame({
    'ds': pd.to_datetime(create_timestamp('2020-01-01')),
    'holiday': 'newyear'
})

seol = pd.DataFrame({
    'ds': pd.to_datetime(create_timestamp('2020-01-24') + create_timestamp('2020-01-25') + create_timestamp('2020-01-26')),
    'holiday': 'seol'
})

seol_alter = pd.DataFrame({
    'ds': pd.to_datetime(create_timestamp('2020-01-27')),
    'holiday': 'seol_alter'
})

day31 = pd.DataFrame({
    'ds': pd.to_datetime(create_timestamp('2020-03-01')),
    'holiday': 'day31'
})

election = pd.DataFrame({
    'ds': pd.to_datetime(create_timestamp('2020-04-15')),
    'holiday': 'election'
})

budda_day = pd.DataFrame({
    'ds': pd.to_datetime(create_timestamp('2020-04-30')),
    'holiday': 'budda_day'
})

children_day = pd.DataFrame({
    'ds': pd.to_datetime(create_timestamp('2020-05-05')),
    'holiday': 'children_day'
})

# memorial_day = pd.DataFrame({
#     'hoilday': 'memorial_day',
#     'ds': pd.to_datetime(create_timestamp('2020-06-06')),
# })

# independence_day = pd.DataFrame({
#     'hoilday': 'independence_day',
#     'ds': pd.to_datetime(create_timestamp('2020-08-15')),
# })

# temp_hoilday = pd.DataFrame({
#     'hoilday': 'temp_hoilday',
#     'ds': pd.to_datetime(create_timestamp('2020-08-17')),
# })

# thanksgiving_day = pd.DataFrame({
#     'hoilday': 'thanksgiving_day',
#     'ds': pd.to_datetime(create_timestamp('2020-09-30'), create_timestamp('2020-10-01'), create_timestamp('2020-10-02')),
# })

# foundation_day = pd.DataFrame({
#     'hoilday': 'foundation_day',
#     'ds': pd.to_datetime(create_timestamp('2020-10-03')),
# })

In [20]:
holidays = pd.concat((newyear, seol, seol_alter, day31, election, budda_day, children_day))

In [21]:
holidays.info()

In [22]:
# Prophet 객체 선언
m = Prophet(
    holidays=holidays
)

# model 학습
m.fit(new_df)

# 예측값 설정
future = m.make_future_dataframe(periods=168, freq='H')

# predict
forecast = m.predict(future)
fig = m.plot(forecast,
            figsize=(40, 15))

fig = m.plot_components(forecast)

In [23]:
cluster_0 = [('101', '남해선(영암-순천)'), ('120', '광주대구선'), ('121', '무안광주선'), ('140', '고창담양선'), ('160', '울산선'), ('201', '익산장수선'), ('251', '호남선'), ('270', '순천완주선'), ('301', '당진대전선'), ('550', '중앙선'), ('652', '동해선(부산-포항)'), ('1020', '남해1지선'), ('2510', '호남지선')]
cluster_1 = [('10', '경부선'), ('100', '남해선(순천-부산)'), ('150', '서해안선'), ('352', '중부선'), ('370', '제2 중부선'), ('400', '평택제천선'), ('450', '중부내륙선'), ('500', '영동선'), ('1000', '서울외곽순환선'), ('1040', '남해2지선'), ('1100', '제2경인선'), ('1200', '경인선'), ('3000', '대전남부선'), ('4510', '중부내륙지선'), ('5510', '중앙선지선'), ('6000', '부산외곽선')]
cluster_2 = [('200', '대구포항선'), ('300', '청주영덕선'), ('351', '통영대전선'), ('600', '서울양양선'), ('650', '동해선(삼척-속초)'), ('1510', '서천공주선')]

In [24]:
from fbprophet.diagnostics import cross_validation, performance_metrics
import itertools

# 남해선
road = '101'

new_df = pd.DataFrame({
    'ds':new_train['날짜'],
    'y':new_train[road]
})

In [25]:
name = 'cluster_0'

config = {
    changepoint : 0.12,
    seasonality : 10,
    weekly : 17,
    daily : 13,
    holiday : 10
    
}

wandb.init(
    config=config,
    project='Prophet',
    tags=['prophet'],
    group='cluster 0',
    name= name,
    notes='cluster 0',
    save_code=True,
)

In [26]:
name = 'cluster_0'

config = {
    'changepoint' : 0.12,
    'seasonality' : 10,
    'weekly' : 17,
    'daily' : 13,
    'holiday' : 10
    
}

wandb.init(
    config=config,
    project='Prophet',
    tags=['prophet'],
    group='cluster 0',
    name= name,
    notes='cluster 0',
    save_code=True,
)

<wandb.sdk.wandb_run.Run at 0x7f4e27473d60>

In [27]:
m = Prophet(changepoint_prior_scale=config[changepoint],
            seasonality_prior_scale=config[seasonality],
            weekly_seasonality=config[weekly],
            daily_seasonality=config[holiday])

m.fit(new_df)
df_cv = cross_validation(m, initial='14 days', period='7 days', horizon='7 days')
df_p = performance_metrics(df_cv)

In [28]:
m = Prophet(changepoint_prior_scale=config['changepoint'],
            seasonality_prior_scale=config['seasonality'],
            weekly_seasonality=config['weekly'],
            daily_seasonality=config['daily'],
            holidays_prior_scale=
           )

m.fit(new_df)
df_cv = cross_validation(m, initial='14 days', period='7 days', horizon='7 days')
df_p = performance_metrics(df_cv)

In [29]:
m = Prophet(changepoint_prior_scale=config['changepoint'],
            seasonality_prior_scale=config['seasonality'],
            weekly_seasonality=config['weekly'],
            daily_seasonality=config['daily'],
            holidays=holidays,
            holidays_prior_scale=config['holiday']
           )

m.fit(new_df)
df_cv = cross_validation(m, initial='14 days', period='7 days', horizon='7 days')
df_p = performance_metrics(df_cv)

In [30]:
print(df_p['rmse'].mean())

wandb.log({
    'rmse':df_p['rmse'].mean()
})
wandb.finish()

In [31]:
new_train.sum()

10      8.084463e+08
100     2.334008e+08
101     2.498295e+07
120     6.072151e+07
121     2.320340e+07
140     1.638828e+07
150     3.468841e+08
160     1.534875e+07
200     3.991463e+07
201     2.184572e+07
251     1.658647e+08
270     4.335454e+07
300     6.918029e+07
301     4.287005e+07
351     9.078815e+07
352     1.512508e+08
370     2.829656e+07
400     7.915625e+07
450     1.673313e+08
500     2.663589e+08
550     1.728434e+08
600     4.888724e+07
650     3.871080e+07
652     2.273921e+07
1000    3.859388e+08
1020    1.800264e+07
1040    3.824057e+07
1100    9.432077e+07
1200    4.865134e+07
1510    1.704667e+07
2510    5.120751e+07
3000    8.521900e+06
4510    4.240068e+07
5510    2.790702e+07
6000    4.885059e+07
dtype: float64

In [32]:
num_list = [x[0] for x in cluster_0
num_list

In [33]:
num_list = [x[0] for x in cluster_0]
num_list

['101',
 '120',
 '121',
 '140',
 '160',
 '201',
 '251',
 '270',
 '301',
 '550',
 '652',
 '1020',
 '2510']

In [34]:
num_list = [x[0] for x in cluster_0]
new_train[num_list]

         101      120     121     140     160     201      251      270  \
0     2611.0   5161.0  1588.0   892.0  1636.0  1894.0  14957.0   3527.0
1     3337.0   5502.0  1650.0  1043.0  1644.0  1967.0  14682.0   3420.0
2     2970.0   4631.0  1044.0   921.0  1104.0  1838.0  11120.0   3587.0
3     2270.0   4242.0  1021.0   790.0   909.0  1630.0   9836.0   3842.0
4     2406.0   3689.0  1840.0   922.0  1354.0  1264.0  10668.0   4559.0
..       ...      ...     ...     ...     ...     ...      ...      ...
331  10625.0  28618.0  8316.0  6684.0  6619.0  8572.0  67748.0  16791.0
332   8226.0  22706.0  6981.0  5743.0  6295.0  7851.0  61609.0  14119.0
333   6002.0  18317.0  4939.0  3779.0  4781.0  6101.0  48336.0  11534.0
334   3575.0  11455.0  3135.0  2536.0  3267.0  4553.0  33607.0   8069.0
335   2242.0   6166.0  1609.0  1391.0  1899.0  2422.0  20343.0   5104.0

         301      550      652    1020     2510
0     2930.0  15393.0   2790.0  1311.0   3810.0
1     3062.0  15834.0   3381.0  1162.0   3763.0
2     3255.0  13866.0   2670.0   768.0   3229.0
3     2661.0  13528.0   2325.0   632.0   2882.0
4     2894.0  18156.0   3583.0   875.0   2433.0
..       ...      ...      ...     ...      ...
331  19124.0  84286.0  10341.0  8254.0  21694.0
332  18610.0  76441.0   8872.0  5225.0  19732.0
333  15651.0  61136.0   6392.0  4072.0  16967.0
334   9723.0  37501.0   3938.0  2489.0  11397.0
335   5413.0  20205.0   2272.0  1343.0   6487.0

[3480 rows x 13 columns]

In [35]:
num_list = [x[0] for x in cluster_0]
new_train[num_list].sum()

101     2.498295e+07
120     6.072151e+07
121     2.320340e+07
140     1.638828e+07
160     1.534875e+07
201     2.184572e+07
251     1.658647e+08
270     4.335454e+07
301     4.287005e+07
550     1.728434e+08
652     2.273921e+07
1020    1.800264e+07
2510    5.120751e+07
dtype: float64

In [36]:
num_list = [x[0] for x in cluster_0]
max(new_train[num_list].sum())

172843406.1666667

In [37]:
num_list = [x[0] for x in cluster_0]
new_train[num_list].sum()

101     2.498295e+07
120     6.072151e+07
121     2.320340e+07
140     1.638828e+07
160     1.534875e+07
201     2.184572e+07
251     1.658647e+08
270     4.335454e+07
301     4.287005e+07
550     1.728434e+08
652     2.273921e+07
1020    1.800264e+07
2510    5.120751e+07
dtype: float64

In [38]:
num_list = [x[0] for x in cluster_0]
new_train[num_list].sum().max()

172843406.1666667

In [39]:
num_list = [x[0] for x in cluster_0]
new_train[num_list].sum().max().index()

In [40]:
num_list = [x[0] for x in cluster_0]
new_train[num_list].sum().idxmax()

'550'

In [41]:
cluster_0 = [('101', '남해선(영암-순천)'), ('120', '광주대구선'), ('121', '무안광주선'), ('140', '고창담양선'), ('160', '울산선'), ('201', '익산장수선'), ('251', '호남선'), ('270', '순천완주선'), ('301', '당진대전선'), ('550', '중앙선'), ('652', '동해선(부산-포항)'), ('1020', '남해1지선'), ('2510', '호남지선')]
cluster_1 = [('10', '경부선'), ('100', '남해선(순천-부산)'), ('150', '서해안선'), ('352', '중부선'), ('370', '제2 중부선'), ('400', '평택제천선'), ('450', '중부내륙선'), ('500', '영동선'), ('1000', '서울외곽순환선'), ('1040', '남해2지선'), ('1100', '제2경인선'), ('1200', '경인선'), ('3000', '대전남부선'), ('4510', '중부내륙지선'), ('5510', '중앙선지선'), ('6000', '부산외곽선')]
cluster_2 = [('200', '대구포항선'), ('300', '청주영덕선'), ('351', '통영대전선'), ('600', '서울양양선'), ('650', '동해선(삼척-속초)'), ('1510', '서천공주선')]

In [42]:
num_list = [x[0] for x in cluster_0]
new_train[num_list].sum().idxmax()

'550'

In [43]:
from fbprophet.diagnostics import cross_validation, performance_metrics
import itertools

num_list = [x[0] for x in cluster_0]
road = new_train[num_list].sum().idxmax()

# 중앙선
# road = '550'

new_df = pd.DataFrame({
    'ds':new_train['날짜'],
    'y':new_train[road]
})

In [44]:
name = 'cluster_0'

cluster_0_params = {
    'changepoint' : 0.12,
    'seasonality' : 10,
    'weekly' : 17,
    'daily' : 13,
    'holiday' : 10
    
}

wandb.init(
    config=cluster_0_params,
    project='Prophet',
    tags=['prophet'],
    group='cluster 0',
    name= name,
    notes='중앙선',
    save_code=True,
)

<wandb.sdk.wandb_run.Run at 0x7f4eaa00efa0>

In [45]:
m = Prophet(changepoint_prior_scale=config['changepoint'],
            seasonality_prior_scale=config['seasonality'],
            weekly_seasonality=config['weekly'],
            daily_seasonality=config['daily'],
            holidays=holidays,
            holidays_prior_scale=config['holiday']
           )

m.fit(new_df)
df_cv = cross_validation(m, initial='14 days', period='7 days', horizon='7 days')
df_p = performance_metrics(df_cv)

In [46]:
print(df_p['rmse'].mean())

wandb.log({
    'rmse':df_p['rmse'].mean()
})
wandb.finish()

In [47]:
from fbprophet.diagnostics import cross_validation, performance_metrics
import itertools

num_list = [x[0] for x in cluster_0]
road = new_train[num_list].sum().idxmax()

# 중앙선
# road = '550'

new_df = pd.DataFrame({
    'ds':new_train['날짜'],
    'y':new_train[road]
})

In [48]:
name = 'cluster_0'

cluster_0_params = {
    'changepoint' : 0.12,
    'seasonality' : 10,
    'weekly' : 17,
    'daily' : 13,
    'holiday' : 11
    
}

wandb.init(
    config=cluster_0_params,
    project='Prophet',
    tags=['prophet'],
    group='cluster 0',
    name= name,
    notes='중앙선',
    save_code=True,
)

<wandb.sdk.wandb_run.Run at 0x7f4ea9db7850>

In [49]:
m = Prophet(changepoint_prior_scale=config['changepoint'],
            seasonality_prior_scale=config['seasonality'],
            weekly_seasonality=config['weekly'],
            daily_seasonality=config['daily'],
            holidays=holidays,
            holidays_prior_scale=config['holiday']
           )

m.fit(new_df)
df_cv = cross_validation(m, initial='14 days', period='7 days', horizon='7 days')
df_p = performance_metrics(df_cv)

In [50]:
print(df_p['rmse'].mean())

wandb.log({
    'rmse':df_p['rmse'].mean()
})
wandb.finish()

In [51]:
name = 'cluster_0'

cluster_0_params = {
    'changepoint' : 0.12,
    'seasonality' : 10,
    'weekly' : 17,
    'daily' : 13,
    'holiday' : 12
    
}

wandb.init(
    config=cluster_0_params,
    project='Prophet',
    tags=['prophet'],
    group='cluster 0',
    name= name,
    notes='중앙선',
    save_code=True,
)

<wandb.sdk.wandb_run.Run at 0x7f4ea9db2730>

In [52]:
m = Prophet(changepoint_prior_scale=config['changepoint'],
            seasonality_prior_scale=config['seasonality'],
            weekly_seasonality=config['weekly'],
            daily_seasonality=config['daily'],
            holidays=holidays,
            holidays_prior_scale=config['holiday']
           )

m.fit(new_df)
df_cv = cross_validation(m, initial='14 days', period='7 days', horizon='7 days')
df_p = performance_metrics(df_cv)

print(df_p['rmse'].mean())

wandb.log({
    'rmse':df_p['rmse'].mean()
})
wandb.finish()

In [53]:
name = 'cluster_0'

cluster_0_params = {
    'changepoint' : 0.12,
    'seasonality' : 10,
    'weekly' : 17,
    'daily' : 13,
    'holiday' : 10
    
}

In [54]:
cluster_0_params['holiday'] += 1

In [55]:
cluster_0_params

{'changepoint': 0.12,
 'seasonality': 10,
 'weekly': 17,
 'daily': 13,
 'holiday': 11}

In [56]:
name = 'cluster_0'

cluster_0_params = {
    'changepoint' : 0.12,
    'seasonality' : 10,
    'weekly' : 17,
    'daily' : 13,
    'holiday' : 10
    
}

In [57]:
name = 'cluster_0'

cluster_0_params = {
    'changepoint' : 0.05,
    'seasonality' : 10,
    'weekly' : 10,
    'daily' : 10,
    'holiday' : 10
    
}

In [58]:
name = 'cluster_0'

cluster_0_params = {
    'changepoint' : 0.05,
    'seasonality' : 10,
    'weekly' : 10,
    'daily' : 10,
    'holiday' : 10
    
}

In [59]:
for i in range(20):
    wandb.init(
        config=cluster_0_params,
        project='Prophet',
        tags=['holiday'],
        group='cluster 0',
        name= name,
        notes='중앙선',
        save_code=True,
    )

    m = Prophet(changepoint_prior_scale=cluster_0_params['changepoint'],
                seasonality_prior_scale=cluster_0_params['seasonality'],
                weekly_seasonality=cluster_0_params['weekly'],
                daily_seasonality=cluster_0_params['daily'],
                holidays=holidays,
                holidays_prior_scale=cluster_0_params['holiday']
               )

    m.fit(new_df)
    df_cv = cross_validation(m, initial='14 days', period='7 days', horizon='7 days')
    df_p = performance_metrics(df_cv)

    print(df_p['rmse'].mean())

    wandb.log({
        'rmse':df_p['rmse'].mean()
    })
    wandb.finish()
    cluster_0_params['holiday'] += 1

In [60]:
name = 'cluster_0'

cluster_0_params = {
    'changepoint' : 0.05,
    'seasonality' : 10,
    'weekly' : 10,
    'daily' : 10,
    'holiday' : 10
    
}

In [61]:
for i in range(20):
    wandb.init(
        config=cluster_0_params,
        project='Prophet',
        tags=['holiday'],
        group='cluster 0',
        name= name,
        notes='중앙선',
        save_code=True,
    )

    m = Prophet(changepoint_prior_scale=cluster_0_params['changepoint'],
                seasonality_prior_scale=cluster_0_params['seasonality'],
                weekly_seasonality=cluster_0_params['weekly'],
                daily_seasonality=cluster_0_params['daily'],
                holidays=holidays,
                holidays_prior_scale=cluster_0_params['holiday']
               )

    m.fit(new_df)
    df_cv = cross_validation(m, initial='14 days', period='7 days', horizon='7 days')
    df_p = performance_metrics(df_cv)

    print(df_p['rmse'].mean())

    wandb.log({
        'rmse':df_p['rmse'].mean()
    })
    wandb.finish()
    cluster_0_params['changepoint'] += 0.01

HBox(children=(HTML(value=''), FloatProgress(value=0.0, max=18.0), HTML(value='')))